language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
    - python3
    - python3-pip

branches:
  only:
    - master
    - stable

install: true

before_script:
    - python3 --version
    - virtualenv -p python3 my_py3
    - source my_py3/bin/activate # to activate the python3 environemt    
    - python -m pip install docutils # use my_py3
    - python -m pip freeze

script: 
  - gradle -Drst2html=`which rst2html.py` build 
deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' upload
    on:
      branch: stable
