language: java
  
branches:
  only:
    - master
    - stable

install: true
  
script: 
  - gradle build 
deploy:
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE upload
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: gradle -Drepos_pwd=${repos_pwd} -Drepos_usr=jql_jars-INTE '-Drelease=' upload
    on:
      branch: stable
