package ch.interlis.models.DM01AVCH24LV95D.Einzelobjekte;
public class EOArt{
  static private java.util.HashMap valuev=new java.util.HashMap();
  private String value=null;
  private EOArt(String value) {
    this.value=value;
    valuev.put(value,this);
  }
  static public String toXmlCode(EOArt value) {
     return value.value;
  }
  static public EOArt parseXmlCode(String value) {
     return (EOArt)valuev.get(value);
  }
  static public EOArt Mauer=new EOArt("Mauer");
  public final static String tag_Mauer="Mauer";
  static public EOArt unterirdisches_Gebaeude=new EOArt("unterirdisches_Gebaeude");
  public final static String tag_unterirdisches_Gebaeude="unterirdisches_Gebaeude";
  static public EOArt uebriger_Gebaeudeteil=new EOArt("uebriger_Gebaeudeteil");
  public final static String tag_uebriger_Gebaeudeteil="uebriger_Gebaeudeteil";
  static public EOArt eingedoltes_oeffentliches_Gewaesser=new EOArt("eingedoltes_oeffentliches_Gewaesser");
  public final static String tag_eingedoltes_oeffentliches_Gewaesser="eingedoltes_oeffentliches_Gewaesser";
  static public EOArt wichtige_Treppe=new EOArt("wichtige_Treppe");
  public final static String tag_wichtige_Treppe="wichtige_Treppe";
  static public EOArt Tunnel_Unterfuehrung_Galerie=new EOArt("Tunnel_Unterfuehrung_Galerie");
  public final static String tag_Tunnel_Unterfuehrung_Galerie="Tunnel_Unterfuehrung_Galerie";
  static public EOArt Bruecke_Passerelle=new EOArt("Bruecke_Passerelle");
  public final static String tag_Bruecke_Passerelle="Bruecke_Passerelle";
  static public EOArt Bahnsteig=new EOArt("Bahnsteig");
  public final static String tag_Bahnsteig="Bahnsteig";
  static public EOArt Brunnen=new EOArt("Brunnen");
  public final static String tag_Brunnen="Brunnen";
  static public EOArt Reservoir=new EOArt("Reservoir");
  public final static String tag_Reservoir="Reservoir";
  static public EOArt Pfeiler=new EOArt("Pfeiler");
  public final static String tag_Pfeiler="Pfeiler";
  static public EOArt Unterstand=new EOArt("Unterstand");
  public final static String tag_Unterstand="Unterstand";
  static public EOArt Silo_Turm_Gasometer=new EOArt("Silo_Turm_Gasometer");
  public final static String tag_Silo_Turm_Gasometer="Silo_Turm_Gasometer";
  static public EOArt Hochkamin=new EOArt("Hochkamin");
  public final static String tag_Hochkamin="Hochkamin";
  static public EOArt Denkmal=new EOArt("Denkmal");
  public final static String tag_Denkmal="Denkmal";
  static public EOArt Mast_Antenne=new EOArt("Mast_Antenne");
  public final static String tag_Mast_Antenne="Mast_Antenne";
  static public EOArt Aussichtsturm=new EOArt("Aussichtsturm");
  public final static String tag_Aussichtsturm="Aussichtsturm";
  static public EOArt Uferverbauung=new EOArt("Uferverbauung");
  public final static String tag_Uferverbauung="Uferverbauung";
  static public EOArt Schwelle=new EOArt("Schwelle");
  public final static String tag_Schwelle="Schwelle";
  static public EOArt Lawinenverbauung=new EOArt("Lawinenverbauung");
  public final static String tag_Lawinenverbauung="Lawinenverbauung";
  static public EOArt massiver_Sockel=new EOArt("massiver_Sockel");
  public final static String tag_massiver_Sockel="massiver_Sockel";
  static public EOArt Ruine_archaeologisches_Objekt=new EOArt("Ruine_archaeologisches_Objekt");
  public final static String tag_Ruine_archaeologisches_Objekt="Ruine_archaeologisches_Objekt";
  static public EOArt Landungssteg=new EOArt("Landungssteg");
  public final static String tag_Landungssteg="Landungssteg";
  static public EOArt einzelner_Fels=new EOArt("einzelner_Fels");
  public final static String tag_einzelner_Fels="einzelner_Fels";
  static public EOArt schmale_bestockte_Flaeche=new EOArt("schmale_bestockte_Flaeche");
  public final static String tag_schmale_bestockte_Flaeche="schmale_bestockte_Flaeche";
  static public EOArt Rinnsal=new EOArt("Rinnsal");
  public final static String tag_Rinnsal="Rinnsal";
  static public EOArt schmaler_Weg=new EOArt("schmaler_Weg");
  public final static String tag_schmaler_Weg="schmaler_Weg";
  static public EOArt Hochspannungsfreileitung=new EOArt("Hochspannungsfreileitung");
  public final static String tag_Hochspannungsfreileitung="Hochspannungsfreileitung";
  static public EOArt Druckleitung=new EOArt("Druckleitung");
  public final static String tag_Druckleitung="Druckleitung";
  static public EOArt Bahngeleise=new EOArt("Bahngeleise");
  public final static String tag_Bahngeleise="Bahngeleise";
  static public EOArt Luftseilbahn=new EOArt("Luftseilbahn");
  public final static String tag_Luftseilbahn="Luftseilbahn";
  static public EOArt Gondelbahn_Sesselbahn=new EOArt("Gondelbahn_Sesselbahn");
  public final static String tag_Gondelbahn_Sesselbahn="Gondelbahn_Sesselbahn";
  static public EOArt Materialseilbahn=new EOArt("Materialseilbahn");
  public final static String tag_Materialseilbahn="Materialseilbahn";
  static public EOArt Skilift=new EOArt("Skilift");
  public final static String tag_Skilift="Skilift";
  static public EOArt Faehre=new EOArt("Faehre");
  public final static String tag_Faehre="Faehre";
  static public EOArt Grotte_Hoehleneingang=new EOArt("Grotte_Hoehleneingang");
  public final static String tag_Grotte_Hoehleneingang="Grotte_Hoehleneingang";
  static public EOArt Achse=new EOArt("Achse");
  public final static String tag_Achse="Achse";
  static public EOArt wichtiger_Einzelbaum=new EOArt("wichtiger_Einzelbaum");
  public final static String tag_wichtiger_Einzelbaum="wichtiger_Einzelbaum";
  static public EOArt Bildstock_Kruzifix=new EOArt("Bildstock_Kruzifix");
  public final static String tag_Bildstock_Kruzifix="Bildstock_Kruzifix";
  static public EOArt Quelle=new EOArt("Quelle");
  public final static String tag_Quelle="Quelle";
  static public EOArt Bezugspunkt=new EOArt("Bezugspunkt");
  public final static String tag_Bezugspunkt="Bezugspunkt";
  static public EOArt weitere=new EOArt("weitere");
  public final static String tag_weitere="weitere";
}
